import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

const poppins=Poppins({subsets:['latin'],weight:'400'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={poppins.className}
        >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
      
  );
}
